---
settings:
  num_images: 2000
  onnx_ep: cuda
  #kasa: ['192.168.1.119', 'jetsonorin']
  pmd: ['/dev/ttyUSB0', ['PCIE1', 'PCIE2']]
  image_path: /home/jquinn/datasets/coco/images/val2017/
models:

  yolov5n-SiLU-416:
    filename: ./onnx_models/yolov5n-SiLU-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 1, 2, 4, 8, 16, 24]

  yolov5n-SiLU-640:
    filename: ./onnx_models/yolov5n-SiLU-dynamic.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov5s-SiLU-416:
    filename: ./onnx_models/yolov5s-SiLU-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov5s-SiLU-640:
    filename: ./onnx_models/yolov5s-SiLU-dynamic.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov7-tiny-416:
    filename: ./onnx_models/yolov7-tiny-416-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov7-tiny-640:
    filename: ./onnx_models/yolov7-tiny-640-dynamic-si.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16]

  yolov8n-416:
    filename: ./onnx_models/yolov8n-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov8s-416:
    filename: ./onnx_models/yolov8s-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov8m-416:
    filename: ./onnx_models/yolov8m-dynamic.onnx
    resolution: 416
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov8n-640:
    filename: ./onnx_models/yolov8n-dynamic.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov8s-640:
    filename: ./onnx_models/yolov8s-dynamic.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16, 24]

  yolov8m-640:
    filename: ./onnx_models/yolov8m-dynamic.onnx
    resolution: 640
    batch_sizes: [1, 2, 4, 8, 16]
