---
settings:
  num_images: 1000
  onnx_ep: cuda
  pmd: ['/dev/ttyCH341USB0', 'PCIE1']
  kasa: ['192.168.1.87', 'workstation']
  image_path: /home/jquinn/datasets/coco/images/val2017/
models:
  yolov5s-LeakyReLU:
    filename: ./models/yolov5s-leakyrelu.onnx
    batch_sizes: [1, 2, 4, 8]
    resolution: 640
