---
settings:
  num_images: 1000
  power: None
  image_path: /home/jquinn/datasets/coco/images/val2017/
models:
  resnet18:
    filename: ./models/resnet18.dfp
    resolution: 224
  yolov5s:
    filename: ./models/yolov5s-leakyrelu_mx3p.dfp
    #post_processing: ./models/model_0_yolov5s-leakyrelu_mx3p_post.onnx
    resolution: 640