---
settings:
  num_images: 1000
  onnx_ep: cuda
  power: pmd
models:
  resnet18:
    filename: ./models/resnet18.onnx
    batch_sizes: [1, 2, 4, 8, 16]
    resolution: 224
  resnet152:
    filename: ./models/resnet152.onnx
    batch_sizes: [1, 2, 4, 8, 16]
    resolution: 224
